version: '3.8'

services:
  todo-service:
    build: ./todo-service
    ports:
      - "3001:8080"
    environment:
      DATABASE_URL: postgres://postgres.nhdpbrknskckotjybrrk:YC6fpEXa2V4Gwjne@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x
      PORT: 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:8080"
    environment:
      TODO_SERVICE_URL: http://todo-service:8080
      PORT: 8080
    depends_on:
      - todo-service

volumes:
  postgres_data: